language: go

go:
  - "1.12.x"

env:
  - GO111MODULE=on

branches:
  only:
    - master

install: skip

before_script:
  - go get golang.org/x/lint
  - export PATH=$GOPATH/bin:$PATH

script:
  - cd chaincode
  - golint
  - go test -v ./...
  - go build
