language: go

go:
  - "1.12.x"

env:
  - GO111MODULE=on

branches:
  only:
    - master

install: skip

before_script:
  - go get golang.org/x/lint/golint

script:
  - cd chaincode
  - go test -v ./...
  - golint_stdout="`go list ./... | grep -v /vendor/ | xargs golint`"
  - go build -v  
  - test -z "$golint_stdout" || (echo -e "FAIL: golint error(s):\n$golint_stdout" && exit 1)

